version: '3'

services:
  authenticate:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017
      - REDIS_URL=redis://127.0.0.1:6379

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
