# Define the version of Docker Compose to use
version: '3'

# Define the services that make up the application
services:

  # Service for authenticating users
  authenticate:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      my-network:
        ipv4_address: 172.16.238.2

  # Service for running a MongoDB database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      my-network:
        ipv4_address: 172.16.238.3

  # Service for running a Redis cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      my-network:
        ipv4_address: 172.16.238.4

# Define the network that the services will use
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
